-- Generated by bun run generate:lean. Edit maintained proofs in Proofs.lean.
import Datamog.Semantics
import Datamog.Records
namespace Datamog.Generated
def successor : Prop :=
  ∀ (v0 : Int) (v1 : Prop) (v2 : Int),
  (((-(9007199254740991 : Int)) <= v0) ∧ (v0 <= (9007199254740991 : Int))) →
  (((-(9007199254740991 : Int)) <= v2) ∧ (v2 <= (9007199254740991 : Int))) →
  (((-(9007199254740991 : Int)) <= (v2 + (1 : Int))) ∧ ((v2 + (1 : Int)) <= (9007199254740991 : Int))) →
  ((v1 ∧ False) ∨ ((¬ v1) ∧ (v0 = (v2 + (1 : Int))))) →
  ((¬ v1) ∧ (v0 > v2))

def falseGoal : Prop :=
  ∀ (v0 : Int),
  (((-(9007199254740991 : Int)) <= v0) ∧ (v0 <= (9007199254740991 : Int))) →
  (v0 > (0 : Int))

inductive Reach (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) : (input0 v0 v1) → Reach input0 v0 v1
  | rule1 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (v2 : Datamog.SafeInt) : (Reach input0 v0 v2) → (input0 v2 v1) → Reach input0 v0 v1

inductive Identity (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) : (input0 v0) → Identity input0 v0 v0

inductive Successor (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (w0.val = v0.val + (1 : Int)) → Successor input0 v0 w0

inductive Guarded (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (v0.val < (9007199254740990 : Int)) → (w0.val = v0.val + (1 : Int)) → Guarded input0 v0 w0

inductive Saturating (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (v0.val < (9007199254740991 : Int)) → (w0.val = v0.val + (1 : Int)) → Saturating input0 v0 w0
  | rule1 (v0 : Datamog.SafeInt) : (input0 v0) → (v0.val ≥ (9007199254740991 : Int)) → Saturating input0 v0 v0

inductive Overlapping (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (v0.val < (9007199254740991 : Int)) → (w0.val = v0.val + (1 : Int)) → Overlapping input0 v0 w0
  | rule1 (v0 : Datamog.SafeInt) : (input0 v0) → (v0.val ≥ (9007199254740990 : Int)) → Overlapping input0 v0 v0

inductive Diagonal (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) : (input0 v0 v1) → (v0.val = v1.val) → Diagonal input0 v0 v1

def reachPreserves : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (P : SafeInt → Prop),
  (∀ a b, edge a b → P a → P b) →
  ∀ a b, Reach edge a b → P a → P b

def reachTransitive : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (a b c : SafeInt),
  Reach edge a b → Reach edge b c → Reach edge a c

def reachUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Reach input0 v0 v1 → Reach input0 v0 w1 → v1 = w1

def identityUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Identity input0 v0 v1 → Identity input0 v0 w1 → v1 = w1

def successorCoverage : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → v0.val < (9007199254740991 : Int) → ∃ (w1 : Datamog.SafeInt), Successor input0 v0 w1

def successorTotal : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → ∃ (w1 : Datamog.SafeInt), Successor input0 v0 w1

def guardedCoverage : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → v0.val < (9007199254740990 : Int) → ∃ (w1 : Datamog.SafeInt), Guarded input0 v0 w1

def guardedTotal : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → ∃ (w1 : Datamog.SafeInt), Guarded input0 v0 w1

def saturatingCoverage : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → ∃ (w1 : Datamog.SafeInt), Saturating input0 v0 w1

def saturatingUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Saturating input0 v0 v1 → Saturating input0 v0 w1 → v1 = w1

def overlappingUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Overlapping input0 v0 v1 → Overlapping input0 v0 w1 → v1 = w1

def diagonalUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Diagonal input0 v0 v1 → Diagonal input0 v0 w1 → v1 = w1

def diagonalTotal : Prop :=
  ∀ (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt),
  input0 v0 v1 → ∃ (w1 : Datamog.SafeInt), Diagonal input0 v0 w1

def recordAbsent : Prop :=
  ∀ (fields : FlatRecord) (key : String),
  (∀ entry ∈ fields, entry.1 ≠ key) → lookupField fields key = none

def recordLastWrite : Prop :=
  ∀ (fields : FlatRecord) (key : String) (value : Value),
  lookupField (fields ++ [(key, value)]) key = some value

def recordNullDistinct : Prop :=
  ∀ (fields : FlatRecord) (key : String),
  lookupField fields key = none →
  lookupField (fields ++ [(key, Value.null)]) key ≠ lookupField fields key

end Datamog.Generated
