-- Generated by bun run generate:lean. Edit maintained proofs in Proofs.lean.
import Datamog.Semantics
namespace Datamog.Generated
def successor : Prop :=
  ∀ (v0 : Int) (v1 : Prop) (v2 : Int),
  (((-(9007199254740991 : Int)) <= v0) ∧ (v0 <= (9007199254740991 : Int))) →
  (((-(9007199254740991 : Int)) <= v2) ∧ (v2 <= (9007199254740991 : Int))) →
  (((-(9007199254740991 : Int)) <= (v2 + (1 : Int))) ∧ ((v2 + (1 : Int)) <= (9007199254740991 : Int))) →
  ((v1 ∧ False) ∨ ((¬ v1) ∧ (v0 = (v2 + (1 : Int))))) →
  ((¬ v1) ∧ (v0 > v2))

def falseGoal : Prop :=
  ∀ (v0 : Int),
  (((-(9007199254740991 : Int)) <= v0) ∧ (v0 <= (9007199254740991 : Int))) →
  (v0 > (0 : Int))

inductive Reach (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) : (input0 v0 v1) → Reach input0 v0 v1
  | rule1 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (v2 : Datamog.SafeInt) : (Reach input0 v0 v2) → (input0 v2 v1) → Reach input0 v0 v1

def reachPreserves : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (P : SafeInt → Prop),
  (∀ a b, edge a b → P a → P b) →
  ∀ a b, Reach edge a b → P a → P b

def reachTransitive : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (a b c : SafeInt),
  Reach edge a b → Reach edge b c → Reach edge a c

inductive Identity (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) : (input0 v0) → Identity input0 v0 v0

def identityUnique : Prop :=
  ∀ (item : SafeInt → Prop) (x y z : SafeInt),
  Identity item x y → Identity item x z → y = z

def reachUnique : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (x y z : SafeInt),
  Reach edge x y → Reach edge x z → y = z

end Datamog.Generated
