-- Generated by bun run generate:lean. Edit maintained proofs in Proofs.lean.
import Datamog.Semantics
import Datamog.Records
import Datamog.NestedRecords
import Datamog.Arrays
import Datamog.NestedArrays
namespace Datamog.Generated
def successor : Prop :=
  ∀ (v0 : Int) (v1 : Prop) (v2 : Int),
  (((-(9007199254740991 : Int)) <= v0) ∧ (v0 <= (9007199254740991 : Int))) →
  (((-(9007199254740991 : Int)) <= v2) ∧ (v2 <= (9007199254740991 : Int))) →
  (((-(9007199254740991 : Int)) <= (v2 + (1 : Int))) ∧ ((v2 + (1 : Int)) <= (9007199254740991 : Int))) →
  ((v1 ∧ False) ∨ ((¬ v1) ∧ (v0 = (v2 + (1 : Int))))) →
  ((¬ v1) ∧ (v0 > v2))

def falseGoal : Prop :=
  ∀ (v0 : Int),
  (((-(9007199254740991 : Int)) <= v0) ∧ (v0 <= (9007199254740991 : Int))) →
  (v0 > (0 : Int))

def NestedArray : List Bool := [false, false]
def NestedArray_lookup : Prop :=
  ∀ (value : Datamog.NestedArrays.Value) (path : List Nat),
  Datamog.NestedArrays.accepts NestedArray false value = true →
  Datamog.NestedArrays.Bounds value path → path.length = 2 →
  ∃ result, Datamog.NestedArrays.lookupPath value path = some result ∧
    Datamog.NestedArrays.accepts [] false result = true

def NullableNestedArray : List Bool := [true, true]
def NullableNestedArray_lookup : Prop :=
  ∀ (value : Datamog.NestedArrays.Value) (path : List Nat),
  Datamog.NestedArrays.accepts NullableNestedArray false value = true →
  Datamog.NestedArrays.Bounds value path → path.length = 2 →
  ∃ result, Datamog.NestedArrays.lookupPath value path = some result ∧
    Datamog.NestedArrays.accepts [] true result = true

def DeepArray : List Bool := [true, true, false]
def DeepArray_lookup : Prop :=
  ∀ (value : Datamog.NestedArrays.Value) (path : List Nat),
  Datamog.NestedArrays.accepts DeepArray false value = true →
  Datamog.NestedArrays.Bounds value path → path.length = 3 →
  ∃ result, Datamog.NestedArrays.lookupPath value path = some result ∧
    Datamog.NestedArrays.accepts [] false result = true

def nestedArrayTypedLookup : Prop :=
  ∀ flags nullable value path, NestedArrays.accepts flags nullable value = true →
  NestedArrays.Bounds value path → path.length = flags.length →
  ∃ result, NestedArrays.lookupPath value path = some result ∧
    NestedArrays.accepts [] (NestedArrays.leafNullable flags nullable) result = true

def nestedArrayTotal_refuted : Prop :=
  ¬ (∀ value, NestedArrays.accepts NullableNestedArray false value = true →
  ∃ result, NestedArrays.lookupPath value [0, 0] = some result)

def IntegerArray : Bool := false
def IntegerArray_lookup : Prop :=
  ∀ (values : List Datamog.Value) (index : Nat),
  Datamog.Arrays.accepts IntegerArray values = true → index < values.length →
  ∃ n : Datamog.SafeInt, Datamog.Arrays.lookupIndex values (Int.ofNat index) = some (.integer n)

def NullableIntegerArray : Bool := true
def NullableIntegerArray_lookup : Prop :=
  ∀ (values : List Datamog.Value) (index : Nat),
  Datamog.Arrays.accepts NullableIntegerArray values = true → index < values.length →
  ∃ value, Datamog.Arrays.lookupIndex values (Int.ofNat index) = some value

def arrayElementValid : Prop :=
  ∀ (nullable : Bool) (values : List Value) (index : Nat) (bound : index < values.length),
  Arrays.accepts nullable values = true → Arrays.elementMatches nullable values[index] = true

def arrayNegativeAbsent : Prop :=
  ∀ (values : List Value) (index : Int), index < 0 → Arrays.lookupIndex values index = none

def arrayPastEndAbsent : Prop :=
  ∀ (values : List Value) (index : Nat), values.length ≤ index →
  Arrays.lookupIndex values (Int.ofNat index) = none

def arrayTotal_refuted : Prop :=
  ∀ nullable : Bool, ¬ (∀ values : List Value, Arrays.accepts nullable values = true →
  ∃ value, Arrays.lookupIndex values 0 = some value)

def NestedSchema : Datamog.Nested.Schema :=
  (Datamog.Nested.Schema.record [((String.ofList [Char.ofNat 114, Char.ofNat 101, Char.ofNat 113, Char.ofNat 117, Char.ofNat 105, Char.ofNat 114, Char.ofNat 101, Char.ofNat 100]), false, false, (Datamog.Nested.Schema.record [((String.ofList [Char.ofNat 105, Char.ofNat 110, Char.ofNat 110, Char.ofNat 101, Char.ofNat 114]), false, false, (Datamog.Nested.Schema.record [((String.ofList [Char.ofNat 110]), false, false, Datamog.Nested.Schema.integer), ((String.ofList [Char.ofNat 110, Char.ofNat 117, Char.ofNat 108, Char.ofNat 108, Char.ofNat 97, Char.ofNat 98, Char.ofNat 108, Char.ofNat 101]), false, true, Datamog.Nested.Schema.integer)]))])), ((String.ofList [Char.ofNat 111, Char.ofNat 112, Char.ofNat 116, Char.ofNat 105, Char.ofNat 111, Char.ofNat 110, Char.ofNat 97, Char.ofNat 108]), true, false, (Datamog.Nested.Schema.record [((String.ofList [Char.ofNat 110]), false, false, Datamog.Nested.Schema.integer)])), ((String.ofList [Char.ofNat 110, Char.ofNat 117, Char.ofNat 108, Char.ofNat 108, Char.ofNat 97, Char.ofNat 98, Char.ofNat 108, Char.ofNat 101]), false, true, (Datamog.Nested.Schema.record [((String.ofList [Char.ofNat 110]), false, false, Datamog.Nested.Schema.integer)])), ((String.ofList [Char.ofNat 109, Char.ofNat 97, Char.ofNat 121, Char.ofNat 98, Char.ofNat 101]), true, true, (Datamog.Nested.Schema.record [((String.ofList [Char.ofNat 110]), false, false, Datamog.Nested.Schema.integer)]))])

def NestedSchema_path0 : Prop :=
  ∀ value : Datamog.Nested.Value, Datamog.Nested.accepts NestedSchema value = true →
  ∃ n : Datamog.SafeInt, Datamog.Nested.lookupPath value [(String.ofList [Char.ofNat 114, Char.ofNat 101, Char.ofNat 113, Char.ofNat 117, Char.ofNat 105, Char.ofNat 114, Char.ofNat 101, Char.ofNat 100]), (String.ofList [Char.ofNat 105, Char.ofNat 110, Char.ofNat 110, Char.ofNat 101, Char.ofNat 114]), (String.ofList [Char.ofNat 110])] = some (.scalar (.integer n))

def NestedSchema_path1 : Prop :=
  ∀ value : Datamog.Nested.Value, Datamog.Nested.accepts NestedSchema value = true →
  ∃ result, Datamog.Nested.lookupPath value [(String.ofList [Char.ofNat 114, Char.ofNat 101, Char.ofNat 113, Char.ofNat 117, Char.ofNat 105, Char.ofNat 114, Char.ofNat 101, Char.ofNat 100]), (String.ofList [Char.ofNat 105, Char.ofNat 110, Char.ofNat 110, Char.ofNat 101, Char.ofNat 114]), (String.ofList [Char.ofNat 110, Char.ofNat 117, Char.ofNat 108, Char.ofNat 108, Char.ofNat 97, Char.ofNat 98, Char.ofNat 108, Char.ofNat 101])] = some result

def nestedRequiredPath : Prop :=
  ∀ (schema : Nested.Schema) (path : List String) (nullable : Bool),
  Nested.RequiredPath schema path nullable → ∀ value,
  Nested.accepts schema value = true →
  ∃ result, Nested.lookupPath value path = some result ∧ Nested.leafMatches nullable result = true

def optionalParentTotal_refuted : Prop :=
  ¬ (∀ value, Nested.accepts NestedSchema value = true →
  ∃ result, Nested.lookupPath value ["optional", "n"] = some result)

def nullableParentTotal_refuted : Prop :=
  ¬ (∀ value, Nested.accepts NestedSchema value = true →
  ∃ result, Nested.lookupPath value ["nullable", "n"] = some result)

def DocumentSchema : List Datamog.IntegerField :=
  [⟨(String.ofList [Char.ofNat 114, Char.ofNat 101, Char.ofNat 113, Char.ofNat 117, Char.ofNat 105, Char.ofNat 114, Char.ofNat 101, Char.ofNat 100]), false, false⟩, ⟨(String.ofList [Char.ofNat 110, Char.ofNat 117, Char.ofNat 108, Char.ofNat 108, Char.ofNat 97, Char.ofNat 98, Char.ofNat 108, Char.ofNat 101]), false, true⟩, ⟨(String.ofList [Char.ofNat 111, Char.ofNat 112, Char.ofNat 116, Char.ofNat 105, Char.ofNat 111, Char.ofNat 110, Char.ofNat 97, Char.ofNat 108]), true, false⟩, ⟨(String.ofList [Char.ofNat 109, Char.ofNat 97, Char.ofNat 121, Char.ofNat 98, Char.ofNat 101]), true, true⟩]

def EmptySchema : List Datamog.IntegerField :=
  []

def DocumentSchema_field0 : Prop :=
  ∀ fields : Datamog.FlatRecord, Datamog.integerRecordMatches DocumentSchema fields = true →
  ∃ n : Datamog.SafeInt, Datamog.lookupField fields (String.ofList [Char.ofNat 114, Char.ofNat 101, Char.ofNat 113, Char.ofNat 117, Char.ofNat 105, Char.ofNat 114, Char.ofNat 101, Char.ofNat 100]) = some (Datamog.Value.integer n)

def DocumentSchema_field1 : Prop :=
  ∀ fields : Datamog.FlatRecord, Datamog.integerRecordMatches DocumentSchema fields = true →
  ∃ value, Datamog.lookupField fields (String.ofList [Char.ofNat 110, Char.ofNat 117, Char.ofNat 108, Char.ofNat 108, Char.ofNat 97, Char.ofNat 98, Char.ofNat 108, Char.ofNat 101]) = some value

inductive Reach (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) : (input0 v0 v1) → Reach input0 v0 v1
  | rule1 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (v2 : Datamog.SafeInt) : (Reach input0 v0 v2) → (input0 v2 v1) → Reach input0 v0 v1

inductive Identity (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) : (input0 v0) → Identity input0 v0 v0

inductive Successor (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (w0.val = v0.val + (1 : Int)) → Successor input0 v0 w0

inductive Guarded (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (v0.val < (9007199254740990 : Int)) → (w0.val = v0.val + (1 : Int)) → Guarded input0 v0 w0

inductive Saturating (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (v0.val < (9007199254740991 : Int)) → (w0.val = v0.val + (1 : Int)) → Saturating input0 v0 w0
  | rule1 (v0 : Datamog.SafeInt) : (input0 v0) → (v0.val ≥ (9007199254740991 : Int)) → Saturating input0 v0 v0

inductive Overlapping (input0 : Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (w0 : Datamog.SafeInt) : (input0 v0) → (v0.val < (9007199254740991 : Int)) → (w0.val = v0.val + (1 : Int)) → Overlapping input0 v0 w0
  | rule1 (v0 : Datamog.SafeInt) : (input0 v0) → (v0.val ≥ (9007199254740990 : Int)) → Overlapping input0 v0 v0

inductive Diagonal (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) : Datamog.SafeInt → Datamog.SafeInt → Prop where
  | rule0 (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) : (input0 v0 v1) → (v0.val = v1.val) → Diagonal input0 v0 v1

def reachPreserves : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (P : SafeInt → Prop),
  (∀ a b, edge a b → P a → P b) →
  ∀ a b, Reach edge a b → P a → P b

def reachTransitive : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (a b c : SafeInt),
  Reach edge a b → Reach edge b c → Reach edge a c

def reachUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Reach input0 v0 v1 → Reach input0 v0 w1 → v1 = w1

def identityUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Identity input0 v0 v1 → Identity input0 v0 w1 → v1 = w1

def successorCoverage : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → v0.val < (9007199254740991 : Int) → ∃ (w1 : Datamog.SafeInt), Successor input0 v0 w1

def successorTotal : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → ∃ (w1 : Datamog.SafeInt), Successor input0 v0 w1

def guardedCoverage : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → v0.val < (9007199254740990 : Int) → ∃ (w1 : Datamog.SafeInt), Guarded input0 v0 w1

def guardedTotal : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → ∃ (w1 : Datamog.SafeInt), Guarded input0 v0 w1

def saturatingCoverage : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt),
  input0 v0 → ∃ (w1 : Datamog.SafeInt), Saturating input0 v0 w1

def saturatingUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Saturating input0 v0 v1 → Saturating input0 v0 w1 → v1 = w1

def overlappingUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Overlapping input0 v0 v1 → Overlapping input0 v0 w1 → v1 = w1

def diagonalUnique : Prop :=
  ∀ (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt) (w1 : Datamog.SafeInt),
  Diagonal input0 v0 v1 → Diagonal input0 v0 w1 → v1 = w1

def diagonalTotal : Prop :=
  ∀ (input0 : Datamog.SafeInt → Datamog.SafeInt → Prop) (v0 : Datamog.SafeInt) (v1 : Datamog.SafeInt),
  input0 v0 v1 → ∃ (w1 : Datamog.SafeInt), Diagonal input0 v0 w1

def schemaFieldMatches : Prop :=
  ∀ (schema : List IntegerField) (fields : FlatRecord) (field : IntegerField),
  field ∈ schema → integerRecordMatches schema fields = true →
  integerFieldMatches fields field.name field.optional field.nullable = true

def schemaClosed : Prop :=
  ∀ (schema : List IntegerField) (fields : FlatRecord),
  integerRecordMatches schema fields = true →
  ∀ entry ∈ fields, ∃ field ∈ schema, field.name = entry.1

def emptySchemaExact : Prop :=
  ∀ fields : FlatRecord, integerRecordMatches [] fields = true ↔ fields = []

def requiredFieldPresent : Prop :=
  ∀ (fields : FlatRecord) (key : String) (nullable : Bool),
  integerFieldMatches fields key false nullable = true →
  ∃ value, lookupField fields key = some value

def nonnullableFieldInteger : Prop :=
  ∀ (fields : FlatRecord) (key : String),
  integerFieldMatches fields key false false = true →
  ∃ n : SafeInt, lookupField fields key = some (Value.integer n)

def optionalFieldTotal_refuted : Prop :=
  ¬ (∀ (fields : FlatRecord) (key : String),
  integerFieldMatches fields key true true = true →
  ∃ value, lookupField fields key = some value)

def recordAbsent : Prop :=
  ∀ (fields : FlatRecord) (key : String),
  (∀ entry ∈ fields, entry.1 ≠ key) → lookupField fields key = none

def recordLastWrite : Prop :=
  ∀ (fields : FlatRecord) (key : String) (value : Value),
  lookupField (fields ++ [(key, value)]) key = some value

def recordNullDistinct : Prop :=
  ∀ (fields : FlatRecord) (key : String),
  lookupField fields key = none →
  lookupField (fields ++ [(key, Value.null)]) key ≠ lookupField fields key

end Datamog.Generated
