input predicate grid(r: integer, c: integer, n: integer).

num(N) :- N in [1..9].
row(N) :- num(N).
col(N) :- num(N).
box(B, R, C) :- row(R), col(C), B = (R-1)/3*3 + (C-1)/3.

in_box(B, N) :- box(B, R, C), grid(R, C, N).

missing_in_row(R, N) :- row(R), num(N), not grid(R, _, N).
missing_in_col(C, N) :- col(C), num(N), not grid(_, C, N).
missing_in_box(B, N) :- box(B, _, _), num(N), not in_box(B, N).

missing(N) :- missing_in_row(_, N).
missing(N) :- missing_in_col(_, N).
missing(N) :- missing_in_box(_, N).

correct() :- not missing(_).

?- correct().
