import { analyze, generateLogicalObligations, inferTypes } from "../packages/core/src/index.ts";
import { exportLeanObligation, exportLeanRelation } from "../packages/core/src/obligation-lean.ts";
import {
  assertCurrentVerificationManifest,
  createVerificationManifest,
  verificationDigest,
} from "../packages/core/src/verification-manifest.ts";
import { parse } from "../packages/parser/src/index.ts";

const root = new URL("../", import.meta.url);
const project = new URL("verification/lean/", root);
const compile = (source: string) => inferTypes(analyze(parse(source)));
const successor = generateLogicalObligations(
  compile(await Bun.file(new URL("doc/invariants/code/08-verify.dl", root)).text()),
);
if (successor.length !== 1 || successor[0]!.dependencies.length)
  throw new Error("Expected one independent successor goal");
const falseGoal = generateLogicalObligations(
  compile("input predicate sample(n: integer). bad(X, _: X > 0) :- sample(X)."),
)[0]!;
const reach = compile(await Bun.file(new URL("fixtures/reach.dl", project)).text());
const successorRelation = compile(await Bun.file(new URL("fixtures/successor.dl", project)).text());
const identity = compile(await Bun.file(new URL("fixtures/identity.dl", project)).text());
// Keep registered relation statements explicit, rather than extracting a range
// of generated text that could accidentally absorb a neighboring declaration.
const reachPreserves = `def reachPreserves : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (P : SafeInt → Prop),
  (∀ a b, edge a b → P a → P b) →
  ∀ a b, Reach edge a b → P a → P b
`;
const reachTransitive = `def reachTransitive : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (a b c : SafeInt),
  Reach edge a b → Reach edge b c → Reach edge a c
`;
const identityUnique = `def identityUnique : Prop :=
  ∀ (item : SafeInt → Prop) (x y z : SafeInt),
  Identity item x y → Identity item x z → y = z
`;
const reachUnique = `def reachUnique : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (x y z : SafeInt),
  Reach edge x y → Reach edge x z → y = z
`;
const successorCoverage = `def successorCoverage : Prop :=
  ∀ (sample : SafeInt → Prop) (x : SafeInt),
  sample x → x.val < maxSafe → ∃ y, Successor sample x y
`;
const successorTotal = `def successorTotal : Prop :=
  ∀ (sample : SafeInt → Prop) (x : SafeInt),
  sample x → ∃ y, Successor sample x y
`;
const generated = `-- Generated by bun run generate:lean. Edit maintained proofs in Proofs.lean.
import Datamog.Semantics
namespace Datamog.Generated
${exportLeanObligation(successor[0]!, "successor")}
${exportLeanObligation(falseGoal, "falseGoal")}
${exportLeanRelation(reach, "reach", "Reach")}
${reachPreserves}
${reachTransitive}
${exportLeanRelation(identity, "identity", "Identity")}
${identityUnique}
${reachUnique}
${exportLeanRelation(successorRelation, "succ", "Successor")}
${successorCoverage}
${successorTotal}
end Datamog.Generated
`;
const checker = `-- Generated: maintained proofs must inhabit these exact types.
import Datamog.Proofs
import Datamog.Audit
namespace Datamog.Checked
theorem successor : Generated.successor := Proofs.successor
theorem reachPreserves : Generated.reachPreserves := Proofs.reachPreserves
#audit successor
#audit reachPreserves
theorem reachTransitive : Generated.reachTransitive := Proofs.reachTransitive
#audit reachTransitive
theorem falseGoal_refuted : ¬ Generated.falseGoal := Proofs.falseGoal_refuted
#audit falseGoal_refuted
theorem identityUnique : Generated.identityUnique := Proofs.identityUnique
#audit identityUnique
theorem reachUnique_refuted : ¬ Generated.reachUnique := Proofs.reachUnique_refuted
#audit reachUnique_refuted
theorem successorCoverage : Generated.successorCoverage := Proofs.successorCoverage
#audit successorCoverage
theorem successorTotal_refuted : ¬ Generated.successorTotal := Proofs.successorTotal_refuted
#audit successorTotal_refuted
end Datamog.Checked
`;
// Hash the full frontend source inventories, not only the exporter entry point:
// an analysis/import change must invalidate a result even if generated text agrees.
const paths = new Set([
  "doc/invariants/code/08-verify.dl",
  "verification/lean/fixtures/reach.dl",
  "verification/lean/fixtures/identity.dl",
  "verification/lean/fixtures/successor.dl",
  "scripts/generate-lean.ts",
  "scripts/test-lean.ts",
  "bun.lock",
  "verification/lean/lean-toolchain",
  "verification/lean/lakefile.toml",
  "verification/lean/lake-manifest.json",
  "verification/lean/Datamog.lean",
]);
for (const directory of ["packages/core/src", "packages/parser/src", "verification/lean/Datamog"]) {
  for await (const path of new Bun.Glob("**/*").scan({
    cwd: new URL(`${directory}/`, root).pathname,
    onlyFiles: true,
  })) {
    if (directory.endsWith("Datamog") && ["Generated.lean", "Checked.lean"].includes(path))
      continue;
    if (/\.(ts|langium|lean)$/.test(path)) paths.add(`${directory}/${path}`);
  }
}
const artifacts: Record<string, string> = {};
for (const path of [...paths].sort())
  artifacts[path] = await verificationDigest(await Bun.file(new URL(path, root)).text());
const manifest = await createVerificationManifest(
  [
    {
      id: "successor",
      theorem: "Datamog.Checked.successor",
      kind: "goal",
      statement: successor[0]!,
      assumptions: [],
      dependencies: [],
    },
    {
      id: "Reach",
      kind: "definition",
      statement: exportLeanRelation(reach, "reach", "Reach"),
      assumptions: [],
      dependencies: [],
    },
    {
      id: "reachPreserves",
      theorem: "Datamog.Checked.reachPreserves",
      kind: "goal",
      statement: reachPreserves,
      assumptions: ["Every input edge preserves P"],
      dependencies: ["Reach"],
    },
    {
      id: "reachTransitive",
      theorem: "Datamog.Checked.reachTransitive",
      kind: "goal",
      statement: reachTransitive,
      assumptions: [],
      dependencies: ["Reach"],
    },
    {
      id: "Identity",
      kind: "definition",
      statement: exportLeanRelation(identity, "identity", "Identity"),
      assumptions: [],
      dependencies: [],
    },
    {
      id: "identityUnique",
      kind: "goal",
      theorem: "Datamog.Checked.identityUnique",
      statement: identityUnique,
      assumptions: [],
      dependencies: ["Identity"],
    },
    {
      id: "reachUnique",
      kind: "definition",
      statement: reachUnique,
      assumptions: [],
      dependencies: ["Reach"],
    },
    {
      id: "reachUnique_refuted",
      kind: "goal",
      theorem: "Datamog.Checked.reachUnique_refuted",
      statement: "¬ Datamog.Generated.reachUnique",
      assumptions: [],
      dependencies: ["reachUnique"],
    },
    {
      id: "Successor",
      kind: "definition",
      statement: exportLeanRelation(successorRelation, "succ", "Successor"),
      assumptions: [],
      dependencies: [],
    },
    {
      id: "successorCoverage",
      kind: "goal",
      theorem: "Datamog.Checked.successorCoverage",
      statement: successorCoverage,
      assumptions: [],
      dependencies: ["Successor"],
    },
    {
      id: "successorTotal",
      kind: "definition",
      statement: successorTotal,
      assumptions: [],
      dependencies: ["Successor"],
    },
    {
      id: "successorTotal_refuted",
      kind: "goal",
      theorem: "Datamog.Checked.successorTotal_refuted",
      statement: "¬ Datamog.Generated.successorTotal",
      assumptions: [],
      dependencies: ["successorTotal"],
    },
    {
      id: "falseGoal",
      kind: "definition",
      statement: falseGoal,
      assumptions: [],
      dependencies: [],
    },
    {
      id: "falseGoal_refuted",
      theorem: "Datamog.Checked.falseGoal_refuted",
      kind: "goal",
      statement: "¬ Datamog.Generated.falseGoal",
      assumptions: [],
      dependencies: ["falseGoal"],
    },
  ],
  {
    profile: "datamog-integer-v1",
    toolchain: (await Bun.file(new URL("lean-toolchain", project)).text()).trim(),
    method: "lean-kernel-checked",
    artifacts,
  },
);
for (const [path, contents] of [
  ["Datamog/Generated.lean", generated],
  ["Datamog/Checked.lean", `-- Verification manifest SHA-256: ${manifest.digest}\n${checker}`],
  ["manifest.json", `${JSON.stringify(manifest, null, 2)}\n`],
]) {
  const target = new URL(path!, project);
  if (process.argv.includes("--check")) {
    if (path === "manifest.json") {
      assertCurrentVerificationManifest(manifest, await Bun.file(target).json());
    }
    if ((await Bun.file(target).text()) !== contents) throw new Error(`Stale Lean output: ${path}`);
  } else await Bun.write(target, contents!);
}
