import { analyze, generateLogicalObligations, inferTypes } from "../packages/core/src/index.ts";
import { exportLeanObligation, exportLeanRelation } from "../packages/core/src/obligation-lean.ts";
import { parse } from "../packages/parser/src/index.ts";

const root = new URL("../", import.meta.url);
const project = new URL("verification/lean/", root);
const compile = (source: string) => inferTypes(analyze(parse(source)));
const successor = generateLogicalObligations(
  compile(await Bun.file(new URL("doc/invariants/code/08-verify.dl", root)).text()),
);
if (successor.length !== 1 || successor[0]!.dependencies.length)
  throw new Error("Expected one independent successor goal");
const falseGoal = generateLogicalObligations(
  compile("input predicate sample(n: integer). bad(X, _: X > 0) :- sample(X)."),
)[0]!;
const reach = compile(await Bun.file(new URL("fixtures/reach.dl", project)).text());
const generated = `-- Generated by bun run generate:lean. Edit maintained proofs in Proofs.lean.
import Datamog.Semantics
namespace Datamog.Generated
${exportLeanObligation(successor[0]!, "successor")}
${exportLeanObligation(falseGoal, "falseGoal")}
${exportLeanRelation(reach, "reach", "Reach")}
def reachPreserves : Prop :=
  ∀ (edge : SafeInt → SafeInt → Prop) (P : SafeInt → Prop),
  (∀ a b, edge a b → P a → P b) →
  ∀ a b, Reach edge a b → P a → P b
end Datamog.Generated
`;
const checker = `-- Generated: maintained proofs must inhabit these exact types.
import Datamog.Proofs
import Datamog.Audit
namespace Datamog.Checked
theorem successor : Generated.successor := Proofs.successor
theorem reachPreserves : Generated.reachPreserves := Proofs.reachPreserves
#audit successor
#audit reachPreserves
theorem falseGoal_refuted : ¬ Generated.falseGoal := Proofs.falseGoal_refuted
#audit falseGoal_refuted
end Datamog.Checked
`;
for (const [path, contents] of [
  ["Datamog/Generated.lean", generated],
  ["Datamog/Checked.lean", checker],
]) {
  const target = new URL(path!, project);
  if (process.argv.includes("--check")) {
    if ((await Bun.file(target).text()) !== contents) throw new Error(`Stale Lean output: ${path}`);
  } else await Bun.write(target, contents!);
}
